version: '3'

services:
  redis:
    image: redis
    restart: always

  backend:
    restart: always
    build: .
    ports: ['8000:8000']
    command: ["python", "./Picasso/manage.py", "runserver", "0.0.0.0:8000"]
    depends_on:
      db:
        condition: service_healthy
    volumes: [./Picasso/media:/app/Picasso/media]

  worker:
    restart: always
    build: .
    volumes: [./Picasso/media:/app/Picasso/media]
    command: ["celery", '--workdir=./Picasso', '-A', 'Picasso', 'worker', '-l', 'info', '-P', 'solo']
    depends_on:
      - redis

  db:
    image: postgres:15.1-alpine
    env_file: .env
    restart: always
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "${POSTGRES_DB}", "-U", "${POSTGRES_USER}"]
      interval: 5s
      retries: 15
      start_period: 15s
